import Head from 'next/head'
import { TasksPage } from '@/features/tasks/tasks'

export default function Home() {
  return (
    <>
      <Head>
        <title>Task Manager App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen">
        <TasksPage />
      </main>
    </>
  )
}
