import Head from "next/head";
import { CreateTodo } from "@/features/create-todo/create-todo";
import { TodosList } from "@/features/todos-list/todos-list";

export default function Home() {
  return (
    <>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen">
        <CreateTodo />
        <TodosList />
      </main>
    </>
  );
}
